-- Supabase Schema for MAXIS (Eris)

CREATE TABLE person_profiles (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    username TEXT UNIQUE,
    password_hash TEXT,
    is_primary_user INTEGER DEFAULT 0,
    face_embedding_json TEXT DEFAULT '[]',
    voice_profile_json TEXT DEFAULT '{}',
    first_met DOUBLE PRECISION DEFAULT 0.0,
    last_seen DOUBLE PRECISION DEFAULT 0.0,
    interaction_count INTEGER DEFAULT 0,
    relationship_label TEXT DEFAULT 'acquaintance',
    preferences_json TEXT DEFAULT '{}',
    traits_json TEXT DEFAULT '[]',
    topics_of_interest_json TEXT DEFAULT '[]',
    warmth_baseline DOUBLE PRECISION DEFAULT 0.3,
    trust_level DOUBLE PRECISION DEFAULT 0.5,
    notes TEXT DEFAULT ''
);
CREATE INDEX idx_person_profiles_name ON person_profiles(name);
CREATE INDEX idx_person_profiles_username ON person_profiles(username);
ALTER TABLE person_profiles ENABLE ROW LEVEL SECURITY;


CREATE TABLE emotional_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp DOUBLE PRECISION NOT NULL,
    person_id TEXT DEFAULT 'unknown',
    event_type TEXT NOT NULL,
    description TEXT DEFAULT '',
    warmth_impact DOUBLE PRECISION DEFAULT 0.0,
    mood_impact DOUBLE PRECISION DEFAULT 0.0,
    energy_impact DOUBLE PRECISION DEFAULT 0.0,
    purpose_impact DOUBLE PRECISION DEFAULT 0.0,
    intensity DOUBLE PRECISION DEFAULT 0.5,
    decay_rate DOUBLE PRECISION DEFAULT 0.1,
    resolved INTEGER DEFAULT 0
);
CREATE INDEX idx_emotional_events_timestamp ON emotional_events(timestamp);
CREATE INDEX idx_emotional_events_person_id ON emotional_events(person_id);
ALTER TABLE emotional_events ENABLE ROW LEVEL SECURITY;


CREATE TABLE chat_sessions (
    id TEXT PRIMARY KEY,
    person_id TEXT,
    title TEXT DEFAULT 'New conversation',
    created_at DOUBLE PRECISION,
    updated_at DOUBLE PRECISION
);
CREATE INDEX idx_chat_sessions_person_id ON chat_sessions(person_id);
ALTER TABLE chat_sessions ENABLE ROW LEVEL SECURITY;


CREATE TABLE chat_messages (
    id TEXT PRIMARY KEY,
    session_id TEXT,
    role TEXT,
    content TEXT,
    timestamp DOUBLE PRECISION
);
CREATE INDEX idx_chat_messages_session_id ON chat_messages(session_id);
ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;


CREATE TABLE procedures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT DEFAULT '',
    steps_json TEXT DEFAULT '[]',
    success_count INTEGER DEFAULT 0,
    failure_count INTEGER DEFAULT 0,
    last_used DOUBLE PRECISION DEFAULT 0.0,
    created_at DOUBLE PRECISION DEFAULT 0.0,
    tags_json TEXT DEFAULT '[]'
);
CREATE INDEX idx_procedures_name ON procedures(name);
ALTER TABLE procedures ENABLE ROW LEVEL SECURITY;


CREATE TABLE knowledge_facts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject TEXT NOT NULL,
    predicate TEXT NOT NULL,
    obj TEXT NOT NULL,
    confidence DOUBLE PRECISION DEFAULT 1.0,
    source TEXT DEFAULT 'conversation',
    timestamp DOUBLE PRECISION DEFAULT 0.0,
    metadata_json TEXT DEFAULT '{}'
);
CREATE INDEX idx_knowledge_facts_subject ON knowledge_facts(subject);
CREATE INDEX idx_knowledge_facts_predicate ON knowledge_facts(predicate);
ALTER TABLE knowledge_facts ENABLE ROW LEVEL SECURITY;

-- Note: Because RLS is enabled, you will need to create policies if you access 
-- the database from a frontend using the anonymous key. If your Python backend 
-- accesses the database directly using the service_role key, it will bypass RLS automatically.
